# Generated by Django 5.1.6 on 2025-11-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="featured",
            field=models.BooleanField(
                default=False, verbose_name="Service mis en avant"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Est publié"),
        ),
    ]
