# Generated by Django 5.1.6 on 2025-12-06 02:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_service", "0002_service_featured_service_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ["-published_at"],
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
            },
        ),
        migrations.AddField(
            model_name="service",
            name="author_email",
            field=models.EmailField(
                default="contact@youssouphamarega.com",
                max_length=254,
                verbose_name="Email de l'auteur",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="author_name",
            field=models.CharField(
                default="Youssoupha Marega",
                max_length=100,
                verbose_name="Nom de l'auteur",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="author_profession",
            field=models.CharField(
                default="Data Scientist",
                max_length=100,
                verbose_name="Profession de l'auteur",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="duration",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Durée (ex: '1 heure', '2 jours')",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Prix (optionnel)",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="published_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date de publication",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de modification"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="calendly_url",
            field=models.URLField(
                blank=True,
                max_length=500,
                verbose_name="Lien Calendly pour réservation",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="content",
            field=models.TextField(verbose_name="Description complète du service"),
        ),
        migrations.AlterField(
            model_name="service",
            name="featured",
            field=models.BooleanField(default=False, verbose_name="Mis en avant"),
        ),
    ]
