# Generated by Django 5.1.6 on 2025-12-06 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_service", "0003_alter_service_options_service_author_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="featured",
        ),
        migrations.RemoveField(
            model_name="service",
            name="is_published",
        ),
    ]
