# Generated by Django 5.1.6 on 2025-12-09 03:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_service", "0004_remove_service_featured_remove_service_is_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="resume",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Résumé"
            ),
        ),
    ]
