# Generated by Django 5.1.6 on 2025-12-09 06:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_service", "0005_alter_service_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Description complète du service"
            ),
        ),
    ]
