# Generated by Django 5.1.6 on 2025-11-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_blog", "0002_alter_blogpost_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="author_email",
            field=models.EmailField(
                default="contact@youssouphamarega.com",
                max_length=254,
                verbose_name="Email de l'auteur",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="author_name",
            field=models.CharField(
                default="Youssoupha Marega",
                max_length=100,
                verbose_name="Nom de l'auteur",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="featured",
            field=models.BooleanField(
                default=False, verbose_name="Article mis en avant"
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Est publié"),
        ),
    ]
