# Generated by Django 5.1.6 on 2025-11-29 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_blog", "0004_blogpost_author_profession"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="author_profession",
        ),
    ]
