# Generated by Django 5.1.6 on 2025-11-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_blog", "0005_remove_blogpost_author_profession"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="author_profession",
            field=models.CharField(
                default="Data Scientist",
                max_length=100,
                verbose_name="Profession de l'auteur",
            ),
        ),
    ]
