# Generated by Django 5.1.6 on 2025-12-06 02:01

import ckeditor_uploader.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_blog", "0006_blogpost_author_profession"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date de création",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blogpost",
            name="read_time",
            field=models.IntegerField(
                default=5, verbose_name="Temps de lecture (minutes)"
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="tags",
            field=models.CharField(
                blank=True,
                max_length=200,
                verbose_name="Tags (séparés par des virgules)",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Contenu de l'article"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="featured",
            field=models.BooleanField(default=False, verbose_name="Mis en avant"),
        ),
    ]
