# Generated by Django 5.1.6 on 2025-12-06 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_blog",
            "0007_blogpost_created_at_blogpost_read_time_blogpost_tags_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="featured",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="is_published",
        ),
    ]
