# Generated by Django 5.1.6 on 2025-12-09 03:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_blog", "0008_remove_blogpost_featured_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="resume",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Résumé"
            ),
        ),
    ]
