# Generated by Django 5.1.6 on 2025-11-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_projet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Est publié"),
        ),
    ]
