# Generated by Django 5.1.6 on 2025-11-29 19:06

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_projet", "0003_rename_created_to_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-published_at"],
                "verbose_name": "Projet",
                "verbose_name_plural": "Projets",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="author_email",
            field=models.EmailField(
                default="contact@youssouphamarega.com",
                max_length=254,
                verbose_name="Email de l'auteur",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="author_name",
            field=models.CharField(
                default="Youssoupha Marega",
                max_length=100,
                verbose_name="Nom de l'auteur",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="author_profession",
            field=models.CharField(
                default="Data Scientist",
                max_length=100,
                verbose_name="Profession de l'auteur",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Contenu"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="published_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de publication"
            ),
        ),
    ]
