# Generated by Django 5.1.6 on 2025-12-06 02:01

import ckeditor_uploader.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_projet", "0004_alter_project_options_project_author_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date de création",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="demo_url",
            field=models.URLField(blank=True, verbose_name="Lien démo"),
        ),
        migrations.AddField(
            model_name="project",
            name="github_url",
            field=models.URLField(blank=True, verbose_name="Lien GitHub"),
        ),
        migrations.AlterField(
            model_name="project",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Contenu détaillé"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="featured",
            field=models.BooleanField(default=False, verbose_name="Mis en avant"),
        ),
    ]
