# Generated by Django 5.1.6 on 2025-12-06 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_projet", "0005_project_created_at_project_demo_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="featured",
        ),
        migrations.RemoveField(
            model_name="project",
            name="is_published",
        ),
    ]
