# Generated by Django 5.1.6 on 2025-12-09 08:04

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("formation", "Formation"),
                            ("experience", "Expérience"),
                            ("competences", "Compétences"),
                            ("stack", "Stack techniques"),
                            ("interets", "Intérêts"),
                            ("valeurs", "Valeurs"),
                            ("custom", "Personnalisé"),
                        ],
                        max_length=20,
                        verbose_name="Type de section",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Titre de la section"
                    ),
                ),
                (
                    "title_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="section_images/",
                        verbose_name="Image du titre",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Afficher cette section"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
            ],
            options={
                "verbose_name": "Section",
                "verbose_name_plural": "Sections",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="SiteProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="Profil par défaut (racine /)"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, verbose_name="Publier ce profil"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL unique pour ce profil (ex: youssoupha-marega-data-scientist)",
                        max_length=255,
                        unique=True,
                        verbose_name="Slug URL",
                    ),
                ),
                ("first_name", models.CharField(max_length=150, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=150, verbose_name="Nom")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Localisation"
                    ),
                ),
                (
                    "profession",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Profession"
                    ),
                ),
                (
                    "current_employer",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Employeur actuel"
                    ),
                ),
                (
                    "current_employer_url",
                    models.URLField(blank=True, verbose_name="Lien employeur"),
                ),
                ("linkedin_url", models.URLField(blank=True, verbose_name="LinkedIn")),
                ("github_url", models.URLField(blank=True, verbose_name="GitHub")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Adresse email"
                    ),
                ),
                ("medium_url", models.URLField(blank=True, verbose_name="Medium")),
                ("youtube_url", models.URLField(blank=True, verbose_name="YouTube")),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile/",
                        verbose_name="Photo de profil",
                    ),
                ),
                (
                    "bio",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, verbose_name="Bio"
                    ),
                ),
                (
                    "bio_position",
                    models.CharField(
                        choices=[
                            ("left", "Colonne gauche"),
                            ("right", "Colonne droite"),
                        ],
                        default="right",
                        max_length=10,
                        verbose_name="Position de la section Profil",
                    ),
                ),
                (
                    "bio_show_title",
                    models.BooleanField(
                        default=True,
                        verbose_name="Afficher le titre de la section Profil",
                    ),
                ),
                (
                    "bio_title",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Titre de la section Profil (facultatif)",
                    ),
                ),
                (
                    "bio_title_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="section_images/",
                        verbose_name="Image du titre Bio",
                    ),
                ),
                (
                    "site_title",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Titre du site (balise <title>)",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="favicon/",
                        verbose_name="Favicon",
                    ),
                ),
                (
                    "navbar_avatar_shape",
                    models.CharField(
                        choices=[
                            ("circle", "Circle"),
                            ("square", "Square"),
                            ("none", "No frame"),
                        ],
                        default="circle",
                        max_length=10,
                        verbose_name="Forme avatar navbar",
                    ),
                ),
                (
                    "navbar_avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="navbar/",
                        verbose_name="Avatar navbar",
                    ),
                ),
                (
                    "projects_home_title",
                    models.CharField(
                        default="Projets mis en avant",
                        max_length=200,
                        verbose_name="Titre section Projets (Accueil)",
                    ),
                ),
                (
                    "projects_home_intro",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True,
                        verbose_name="Texte d'introduction Projets (Accueil)",
                    ),
                ),
                (
                    "projects_navbar_label",
                    models.CharField(
                        default="Projets",
                        max_length=100,
                        verbose_name="Label navbar Projets",
                    ),
                ),
                (
                    "projects_page_title",
                    models.CharField(
                        default="Mes Projets",
                        max_length=200,
                        verbose_name="Titre page liste Projets",
                    ),
                ),
                (
                    "projects_page_intro",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, verbose_name="Texte d'introduction page Projets"
                    ),
                ),
                (
                    "projects_view_all_text",
                    models.CharField(
                        default="Voir tous les projets",
                        max_length=100,
                        verbose_name="Texte 'Voir tous les projets'",
                    ),
                ),
                (
                    "projects_detail_button_text",
                    models.CharField(
                        default="Voir le projet",
                        max_length=100,
                        verbose_name="Texte bouton détail projet",
                    ),
                ),
                (
                    "projects_back_button_text",
                    models.CharField(
                        default="Retour aux projets",
                        max_length=100,
                        verbose_name="Texte bouton retour projets",
                    ),
                ),
                (
                    "blog_home_title",
                    models.CharField(
                        default="Articles de blog mis en avant",
                        max_length=200,
                        verbose_name="Titre section Blog (Accueil)",
                    ),
                ),
                (
                    "blog_home_intro",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, verbose_name="Texte d'introduction Blog (Accueil)"
                    ),
                ),
                (
                    "blog_navbar_label",
                    models.CharField(
                        default="Blogue",
                        max_length=100,
                        verbose_name="Label navbar Blog",
                    ),
                ),
                (
                    "blog_page_title",
                    models.CharField(
                        default="Articles de blog",
                        max_length=200,
                        verbose_name="Titre page liste Blog",
                    ),
                ),
                (
                    "blog_page_intro",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, verbose_name="Texte d'introduction page Blog"
                    ),
                ),
                (
                    "blog_view_all_text",
                    models.CharField(
                        default="Voir tous les articles",
                        max_length=100,
                        verbose_name="Texte 'Voir tous les articles'",
                    ),
                ),
                (
                    "blog_detail_button_text",
                    models.CharField(
                        default="Lire l'article",
                        max_length=100,
                        verbose_name="Texte bouton lire article",
                    ),
                ),
                (
                    "blog_back_button_text",
                    models.CharField(
                        default="Retour aux articles",
                        max_length=100,
                        verbose_name="Texte bouton retour articles",
                    ),
                ),
                (
                    "services_home_title",
                    models.CharField(
                        default="Services",
                        max_length=200,
                        verbose_name="Titre section Services (Accueil)",
                    ),
                ),
                (
                    "services_home_intro",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True,
                        verbose_name="Texte d'introduction Services (Accueil)",
                    ),
                ),
                (
                    "services_navbar_label",
                    models.CharField(
                        default="Services",
                        max_length=100,
                        verbose_name="Label navbar Services",
                    ),
                ),
                (
                    "services_page_title",
                    models.CharField(
                        default="Services offerts",
                        max_length=200,
                        verbose_name="Titre page liste Services",
                    ),
                ),
                (
                    "services_page_intro",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, verbose_name="Texte d'introduction page Services"
                    ),
                ),
                (
                    "services_view_all_text",
                    models.CharField(
                        default="Voir tous les services",
                        max_length=100,
                        verbose_name="Texte 'Voir tous les services'",
                    ),
                ),
                (
                    "services_detail_button_text",
                    models.CharField(
                        default="En savoir plus",
                        max_length=100,
                        verbose_name="Texte bouton détail service",
                    ),
                ),
                (
                    "services_back_button_text",
                    models.CharField(
                        default="Retour aux services",
                        max_length=100,
                        verbose_name="Texte bouton retour services",
                    ),
                ),
                (
                    "services_calendly_button_text",
                    models.CharField(
                        default="Prendre rendez-vous",
                        max_length=100,
                        verbose_name="Texte bouton Calendly",
                    ),
                ),
                (
                    "projects_home_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="section_images/",
                        verbose_name="Image section Projets (Accueil)",
                    ),
                ),
                (
                    "projects_page_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="section_images/",
                        verbose_name="Image page liste Projets",
                    ),
                ),
                (
                    "blog_home_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="section_images/",
                        verbose_name="Image section Blog (Accueil)",
                    ),
                ),
                (
                    "blog_page_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="section_images/",
                        verbose_name="Image page liste Blog",
                    ),
                ),
                (
                    "services_home_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="section_images/",
                        verbose_name="Image section Services (Accueil)",
                    ),
                ),
                (
                    "services_page_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="section_images/",
                        verbose_name="Image page liste Services",
                    ),
                ),
                (
                    "projects_display_order",
                    models.PositiveIntegerField(
                        default=2, verbose_name="Ordre d'affichage Projets"
                    ),
                ),
                (
                    "blog_display_order",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Ordre d'affichage Blog"
                    ),
                ),
                (
                    "services_display_order",
                    models.PositiveIntegerField(
                        default=4, verbose_name="Ordre d'affichage Services"
                    ),
                ),
                (
                    "contact_display_order",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Ordre d'affichage Contact"
                    ),
                ),
                (
                    "contact_title",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Titre de la section Contact",
                    ),
                ),
                (
                    "contact_title_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="section_images/",
                        verbose_name="Image du titre Contact",
                    ),
                ),
                (
                    "contact_intro_text",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, verbose_name="Texte d'introduction Contact"
                    ),
                ),
                (
                    "contact_name_label",
                    models.CharField(
                        default="Nom complet",
                        max_length=100,
                        verbose_name="Label champ Nom",
                    ),
                ),
                (
                    "contact_email_label",
                    models.CharField(
                        default="Adresse email",
                        max_length=100,
                        verbose_name="Label champ Email",
                    ),
                ),
                (
                    "contact_company_label",
                    models.CharField(
                        default="Entreprise",
                        max_length=100,
                        verbose_name="Label champ Entreprise",
                    ),
                ),
                (
                    "contact_profession_label",
                    models.CharField(
                        default="Profession",
                        max_length=100,
                        verbose_name="Label champ Profession",
                    ),
                ),
                (
                    "contact_subject_label",
                    models.CharField(
                        default="Objet",
                        max_length=100,
                        verbose_name="Label champ Objet",
                    ),
                ),
                (
                    "contact_message_label",
                    models.CharField(
                        default="Votre message",
                        max_length=100,
                        verbose_name="Label champ Message",
                    ),
                ),
                (
                    "contact_button_text",
                    models.CharField(
                        default="Envoyer le message",
                        max_length=100,
                        verbose_name="Texte du bouton",
                    ),
                ),
                (
                    "contact_success_message",
                    models.TextField(
                        default="Merci ! Votre message a été envoyé avec succès. Nous vous répondrons dans les plus brefs délais.",
                        verbose_name="Message de succès",
                    ),
                ),
                (
                    "contact_error_message",
                    models.TextField(
                        default="Une erreur s'est produite lors de l'envoi de votre message. Veuillez réessayer.",
                        verbose_name="Message d'erreur",
                    ),
                ),
                (
                    "enable_confirmation_email",
                    models.BooleanField(
                        default=True,
                        verbose_name="Envoyer un email de confirmation à l'expéditeur",
                    ),
                ),
                (
                    "gmail_app_password",
                    models.CharField(
                        blank=True,
                        help_text="Requis pour envoyer des emails. Créez-le sur https://myaccount.google.com/apppasswords",
                        max_length=100,
                        verbose_name="Mot de passe d'application Gmail",
                    ),
                ),
                (
                    "projects_show_author_home",
                    models.BooleanField(default=True, verbose_name="Auteur"),
                ),
                (
                    "projects_show_author_list",
                    models.BooleanField(default=True, verbose_name="Auteur"),
                ),
                (
                    "projects_show_author_detail",
                    models.BooleanField(default=True, verbose_name="Auteur"),
                ),
                (
                    "projects_show_profession_home",
                    models.BooleanField(default=True, verbose_name="Profession"),
                ),
                (
                    "projects_show_profession_list",
                    models.BooleanField(default=True, verbose_name="Profession"),
                ),
                (
                    "projects_show_profession_detail",
                    models.BooleanField(default=True, verbose_name="Profession"),
                ),
                (
                    "projects_show_publish_date_home",
                    models.BooleanField(default=True, verbose_name="Date pub"),
                ),
                (
                    "projects_show_publish_date_list",
                    models.BooleanField(default=True, verbose_name="Date pub"),
                ),
                (
                    "projects_show_publish_date_detail",
                    models.BooleanField(default=True, verbose_name="Date pub"),
                ),
                (
                    "projects_show_update_date_home",
                    models.BooleanField(default=True, verbose_name="Date MAJ"),
                ),
                (
                    "projects_show_update_date_list",
                    models.BooleanField(default=True, verbose_name="Date MAJ"),
                ),
                (
                    "projects_show_update_date_detail",
                    models.BooleanField(default=True, verbose_name="Date MAJ"),
                ),
                (
                    "blog_show_author_home",
                    models.BooleanField(default=True, verbose_name="Auteur"),
                ),
                (
                    "blog_show_author_list",
                    models.BooleanField(default=True, verbose_name="Auteur"),
                ),
                (
                    "blog_show_author_detail",
                    models.BooleanField(default=True, verbose_name="Auteur"),
                ),
                (
                    "blog_show_profession_home",
                    models.BooleanField(default=True, verbose_name="Profession"),
                ),
                (
                    "blog_show_profession_list",
                    models.BooleanField(default=True, verbose_name="Profession"),
                ),
                (
                    "blog_show_profession_detail",
                    models.BooleanField(default=True, verbose_name="Profession"),
                ),
                (
                    "blog_show_publish_date_home",
                    models.BooleanField(default=True, verbose_name="Date pub"),
                ),
                (
                    "blog_show_publish_date_list",
                    models.BooleanField(default=True, verbose_name="Date pub"),
                ),
                (
                    "blog_show_publish_date_detail",
                    models.BooleanField(default=True, verbose_name="Date pub"),
                ),
                (
                    "blog_show_update_date_home",
                    models.BooleanField(default=True, verbose_name="Date MAJ"),
                ),
                (
                    "blog_show_update_date_list",
                    models.BooleanField(default=True, verbose_name="Date MAJ"),
                ),
                (
                    "blog_show_update_date_detail",
                    models.BooleanField(default=True, verbose_name="Date MAJ"),
                ),
                (
                    "services_show_author_home",
                    models.BooleanField(default=True, verbose_name="Auteur"),
                ),
                (
                    "services_show_author_list",
                    models.BooleanField(default=True, verbose_name="Auteur"),
                ),
                (
                    "services_show_author_detail",
                    models.BooleanField(default=True, verbose_name="Auteur"),
                ),
                (
                    "services_show_profession_home",
                    models.BooleanField(default=True, verbose_name="Profession"),
                ),
                (
                    "services_show_profession_list",
                    models.BooleanField(default=True, verbose_name="Profession"),
                ),
                (
                    "services_show_profession_detail",
                    models.BooleanField(default=True, verbose_name="Profession"),
                ),
                (
                    "services_show_publish_date_home",
                    models.BooleanField(default=True, verbose_name="Date pub"),
                ),
                (
                    "services_show_publish_date_list",
                    models.BooleanField(default=True, verbose_name="Date pub"),
                ),
                (
                    "services_show_publish_date_detail",
                    models.BooleanField(default=True, verbose_name="Date pub"),
                ),
                (
                    "services_show_update_date_home",
                    models.BooleanField(default=True, verbose_name="Date MAJ"),
                ),
                (
                    "services_show_update_date_list",
                    models.BooleanField(default=True, verbose_name="Date MAJ"),
                ),
                (
                    "services_show_update_date_detail",
                    models.BooleanField(default=True, verbose_name="Date MAJ"),
                ),
                (
                    "navbar_position",
                    models.CharField(
                        choices=[("left", "Gauche"), ("right", "Droite")],
                        default="left",
                        help_text="Choisir si la barre de navigation doit être à gauche ou à droite",
                        max_length=10,
                        verbose_name="Position de la barre de navigation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil du site",
                "verbose_name_plural": "Profils du site",
            },
        ),
        migrations.CreateModel(
            name="SectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="sections/",
                        verbose_name="Icône",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Titre principal"),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Sous-titre / Détails (ex: institution, entreprise)",
                    ),
                ),
                (
                    "date",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Date / Période (ex: 2023, 2022-2023)",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        verbose_name="Lien (optionnel, ex: site de l'entreprise)",
                    ),
                ),
                (
                    "details",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="Détails"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="app_acceuil.section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Élément de section",
                "verbose_name_plural": "Éléments de section",
                "ordering": ("order",),
            },
        ),
        migrations.AddField(
            model_name="section",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="app_acceuil.siteprofile",
            ),
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Intitulé / Poste"),
                ),
                (
                    "date",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Date / Période"
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Entreprise"
                    ),
                ),
                (
                    "company_url",
                    models.URLField(blank=True, verbose_name="Lien entreprise"),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="experience/",
                        verbose_name="Icône",
                    ),
                ),
                (
                    "details",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="Détails de l'expérience"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="app_acceuil.siteprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expérience",
                "verbose_name_plural": "Expériences",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Titre de la formation"
                    ),
                ),
                (
                    "date",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Date / Années"
                    ),
                ),
                (
                    "institution",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Établissement"
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="education/",
                        verbose_name="Icône",
                    ),
                ),
                (
                    "details",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="Détails de la formation"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations",
                        to="app_acceuil.siteprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Formation",
                "verbose_name_plural": "Formations",
                "ordering": ("order",),
            },
        ),
    ]
