# Generated by Django 5.1.6 on 2025-11-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_acceuil", "0003_branding_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteprofile",
            name="navbar_avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="navbar/", verbose_name="Avatar navbar"
            ),
        ),
    ]
