# Generated by Django 5.1.6 on 2025-12-01 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_acceuil", "0004_siteprofile_navbar_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("competences", "Compétences"),
                            ("stack", "Stack techniques"),
                            ("interets", "Intérêts"),
                            ("valeurs", "Valeurs"),
                            ("custom", "Personnalisé"),
                        ],
                        max_length=20,
                        verbose_name="Type de section",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Titre de la section"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Afficher cette section"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="app_acceuil.siteprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Section",
                "verbose_name_plural": "Sections",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="SectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="sections/",
                        verbose_name="Icône",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Titre principal"),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Sous-titre / Détails"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="app_acceuil.section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Élément de section",
                "verbose_name_plural": "Éléments de section",
                "ordering": ("order",),
            },
        ),
    ]
