# Generated by Django 5.1.6 on 2025-12-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_acceuil", "0005_section_sectionitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to="education/", verbose_name="Icône"
            ),
        ),
        migrations.AddField(
            model_name="experience",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to="experience/", verbose_name="Icône"
            ),
        ),
    ]
