# Generated by Django A.I. helper
from django.db import migrations, models
import ckeditor.fields

class Migration(migrations.Migration):

    dependencies = [
        ('app_acceuil', '0006_education_icon_experience_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Détails de la formation'),
        ),
    ]
