# Generated by Django A.I. helper
from django.db import migrations, models
import ckeditor.fields

class Migration(migrations.Migration):

    dependencies = [
        ('app_acceuil', '0007_add_education_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="Détails de l'expérience"),
        ),
    ]
