# Generated by Django A.I. helper
from django.db import migrations, models
import ckeditor.fields

class Migration(migrations.Migration):

    dependencies = [
        ('app_acceuil', '0008_add_experience_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionitem',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Détails'),
        ),
    ]
