# Generated by Django A.I. helper
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('app_acceuil', '0009_add_sectionitem_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='bio_position',
            field=models.CharField(choices=[('left', 'Colonne gauche'), ('right', 'Colonne droite')], default='right', max_length=10, verbose_name='Position de la section Profil'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='bio_show_title',
            field=models.BooleanField(default=True, verbose_name='Afficher le titre de la section Profil'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='bio_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Titre de la section Profil (facultatif)'),
        ),
    ]
