# Generated by Django 5.1.6 on 2025-12-05 20:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_acceuil", "0010_siteprofile_bio_controls"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteprofile",
            name="projects_home_intro",
            field=ckeditor.fields.RichTextField(
                blank=True, verbose_name="Texte d'introduction Projets (Accueil)"
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="projects_home_title",
            field=models.CharField(
                default="Projets mis en avant",
                max_length=200,
                verbose_name="Titre section Projets (Accueil)",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="projects_navbar_label",
            field=models.CharField(
                default="Projets", max_length=100, verbose_name="Label navbar Projets"
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="projects_page_intro",
            field=ckeditor.fields.RichTextField(
                blank=True, verbose_name="Texte d'introduction page Projets"
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="projects_page_title",
            field=models.CharField(
                default="Mes Projets",
                max_length=200,
                verbose_name="Titre page liste Projets",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="projects_view_all_text",
            field=models.CharField(
                default="Voir tous les projets",
                max_length=100,
                verbose_name="Texte 'Voir tous les projets'",
            ),
        ),
    ]
