# Generated by Django 5.1.6 on 2025-12-05 21:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_acceuil", "0011_siteprofile_projects_home_intro_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteprofile",
            name="blog_home_intro",
            field=ckeditor.fields.RichTextField(
                blank=True, verbose_name="Texte d'introduction Blog (Accueil)"
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="blog_home_title",
            field=models.CharField(
                default="Articles de blog mis en avant",
                max_length=200,
                verbose_name="Titre section Blog (Accueil)",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="blog_navbar_label",
            field=models.CharField(
                default="Blogue", max_length=100, verbose_name="Label navbar Blog"
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="blog_page_intro",
            field=ckeditor.fields.RichTextField(
                blank=True, verbose_name="Texte d'introduction page Blog"
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="blog_page_title",
            field=models.CharField(
                default="Articles de blog",
                max_length=200,
                verbose_name="Titre page liste Blog",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="blog_view_all_text",
            field=models.CharField(
                default="Voir tous les articles",
                max_length=100,
                verbose_name="Texte 'Voir tous les articles'",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="services_navbar_label",
            field=models.CharField(
                default="Services", max_length=100, verbose_name="Label navbar Services"
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="services_page_intro",
            field=ckeditor.fields.RichTextField(
                blank=True, verbose_name="Texte d'introduction page Services"
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="services_page_title",
            field=models.CharField(
                default="Services offerts",
                max_length=200,
                verbose_name="Titre page liste Services",
            ),
        ),
    ]
