# Generated by Django 5.1.6 on 2025-12-05 21:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_acceuil", "0012_siteprofile_blog_home_intro_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteprofile",
            name="services_home_intro",
            field=ckeditor.fields.RichTextField(
                blank=True, verbose_name="Texte d'introduction Services (Accueil)"
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="services_home_title",
            field=models.CharField(
                default="Services",
                max_length=200,
                verbose_name="Titre section Services (Accueil)",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="services_view_all_text",
            field=models.CharField(
                default="Voir tous les services",
                max_length=100,
                verbose_name="Texte 'Voir tous les services'",
            ),
        ),
    ]
