# Generated by Django 5.1.6 on 2025-12-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_acceuil", "0013_siteprofile_services_home_intro_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="siteprofile",
            options={
                "verbose_name": "Profil du site",
                "verbose_name_plural": "Profils du site",
            },
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Profil actif"),
        ),
    ]
