# Generated by Django 5.1.6 on 2025-12-05 21:39

from django.db import migrations, models
from django.utils.text import slugify


def generate_unique_slugs(apps, schema_editor):
    """Génère des slugs uniques pour les profils existants"""
    SiteProfile = apps.get_model('app_acceuil', 'SiteProfile')
    
    for index, profile in enumerate(SiteProfile.objects.all(), start=1):
        # Créer un slug basé sur first_name, last_name et profession
        base_slug = slugify(f"{profile.first_name}-{profile.last_name}-{profile.profession or 'profil'}")
        
        # Si le slug existe déjà, ajouter un numéro
        slug = base_slug
        counter = 1
        while SiteProfile.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        
        profile.slug = slug
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ("app_acceuil", "0014_alter_siteprofile_options_siteprofile_is_active"),
        ("app_blog", "0006_blogpost_author_profession"),
        ("app_projet", "0004_alter_project_options_project_author_email_and_more"),
        ("app_service", "0002_service_featured_service_is_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteprofile",
            name="featured_articles",
            field=models.ManyToManyField(
                blank=True,
                related_name="featured_in_profiles",
                to="app_blog.blogpost",
                verbose_name="Articles mis en avant",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="featured_projects",
            field=models.ManyToManyField(
                blank=True,
                related_name="featured_in_profiles",
                to="app_projet.project",
                verbose_name="Projets mis en avant",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="featured_services",
            field=models.ManyToManyField(
                blank=True,
                related_name="featured_in_profiles",
                to="app_service.service",
                verbose_name="Services mis en avant",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="is_default",
            field=models.BooleanField(
                default=False, verbose_name="Profil par défaut (racine /)"
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Publier ce profil"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="published_articles",
            field=models.ManyToManyField(
                blank=True,
                related_name="profiles",
                to="app_blog.blogpost",
                verbose_name="Articles publiés",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="published_projects",
            field=models.ManyToManyField(
                blank=True,
                related_name="profiles",
                to="app_projet.project",
                verbose_name="Projets publiés",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="published_services",
            field=models.ManyToManyField(
                blank=True,
                related_name="profiles",
                to="app_service.service",
                verbose_name="Services publiés",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="slug",
            field=models.SlugField(
                default="temp-slug",
                help_text="URL unique pour ce profil (ex: youssoupha-marega-data-scientist)",
                max_length=255,
                verbose_name="Slug URL",
            ),
            preserve_default=False,
        ),
        # Générer des slugs uniques pour les profils existants
        migrations.RunPython(generate_unique_slugs, migrations.RunPython.noop),
        # Ajouter la contrainte unique après avoir généré les slugs
        migrations.AlterField(
            model_name="siteprofile",
            name="slug",
            field=models.SlugField(
                help_text="URL unique pour ce profil (ex: youssoupha-marega-data-scientist)",
                max_length=255,
                unique=True,
                verbose_name="Slug URL",
            ),
        ),
    ]
