# Generated by Django 5.1.6 on 2025-12-05 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_acceuil", "0015_siteprofile_featured_articles_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteprofile",
            name="is_active",
        ),
    ]
