# Generated by Django 5.1.6 on 2025-12-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_acceuil", "0016_remove_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionitem",
            name="url",
            field=models.URLField(
                blank=True, verbose_name="Lien (optionnel, ex: site de l'entreprise)"
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("formation", "Formation"),
                    ("experience", "Expérience"),
                    ("competences", "Compétences"),
                    ("stack", "Stack techniques"),
                    ("interets", "Intérêts"),
                    ("valeurs", "Valeurs"),
                    ("custom", "Personnalisé"),
                ],
                max_length=20,
                verbose_name="Type de section",
            ),
        ),
        migrations.AlterField(
            model_name="sectionitem",
            name="subtitle",
            field=models.CharField(
                blank=True,
                max_length=500,
                verbose_name="Sous-titre / Détails (ex: institution, entreprise, période)",
            ),
        ),
    ]
