# Generated by Django 5.1.6 on 2025-12-06 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_acceuil", "0017_sectionitem_url_alter_section_section_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteprofile",
            name="chip_color",
        ),
        migrations.RemoveField(
            model_name="siteprofile",
            name="chip_shape",
        ),
        migrations.RemoveField(
            model_name="siteprofile",
            name="chip_text",
        ),
        migrations.RemoveField(
            model_name="siteprofile",
            name="chip_title",
        ),
        migrations.RemoveField(
            model_name="siteprofile",
            name="chip_use_photo",
        ),
        migrations.RemoveField(
            model_name="siteprofile",
            name="show_chip",
        ),
    ]
