# Generated by Django 5.1.6 on 2025-12-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_acceuil", "0018_remove_siteprofile_chip_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionitem",
            name="date",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Date / Période (ex: 2023, 2022-2023)",
            ),
        ),
        migrations.AlterField(
            model_name="sectionitem",
            name="subtitle",
            field=models.CharField(
                blank=True,
                max_length=500,
                verbose_name="Sous-titre / Détails (ex: institution, entreprise)",
            ),
        ),
    ]
