# Generated by Django 5.1.6 on 2025-12-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_acceuil", "0019_sectionitem_date_alter_sectionitem_subtitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteprofile",
            name="medium_url",
            field=models.URLField(blank=True, verbose_name="Medium"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="youtube_url",
            field=models.URLField(blank=True, verbose_name="YouTube"),
        ),
    ]
