# Generated by Django 5.1.6 on 2025-12-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_acceuil", "0020_siteprofile_medium_url_siteprofile_youtube_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteprofile",
            name="blog_back_button_text",
            field=models.CharField(
                default="Retour aux articles",
                max_length=100,
                verbose_name="Texte bouton retour articles",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="blog_detail_button_text",
            field=models.CharField(
                default="Lire l'article",
                max_length=100,
                verbose_name="Texte bouton lire article",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="projects_back_button_text",
            field=models.CharField(
                default="Retour aux projets",
                max_length=100,
                verbose_name="Texte bouton retour projets",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="projects_detail_button_text",
            field=models.CharField(
                default="Voir le projet",
                max_length=100,
                verbose_name="Texte bouton détail projet",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="services_back_button_text",
            field=models.CharField(
                default="Retour aux services",
                max_length=100,
                verbose_name="Texte bouton retour services",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="services_detail_button_text",
            field=models.CharField(
                default="En savoir plus",
                max_length=100,
                verbose_name="Texte bouton détail service",
            ),
        ),
    ]
