# Generated by Django 5.1.6 on 2025-12-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_acceuil", "0021_siteprofile_blog_back_button_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteprofile",
            name="services_calendly_button_text",
            field=models.CharField(
                default="Prendre rendez-vous",
                max_length=100,
                verbose_name="Texte bouton Calendly",
            ),
        ),
    ]
