# Generated by Django 5.1.6 on 2025-12-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_acceuil", "0022_siteprofile_services_calendly_button_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="title_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="section_images/",
                verbose_name="Image du titre",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="bio_section_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="section_images/",
                verbose_name="Image section Bio",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="blog_home_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="section_images/",
                verbose_name="Image section Blog (Accueil)",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="blog_page_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="section_images/",
                verbose_name="Image page liste Blog",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="competences_section_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="section_images/",
                verbose_name="Image section Compétences",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="experience_section_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="section_images/",
                verbose_name="Image section Expérience",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="formation_section_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="section_images/",
                verbose_name="Image section Formation",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="interets_section_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="section_images/",
                verbose_name="Image section Intérêts",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="projects_home_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="section_images/",
                verbose_name="Image section Projets (Accueil)",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="projects_page_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="section_images/",
                verbose_name="Image page liste Projets",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="services_home_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="section_images/",
                verbose_name="Image section Services (Accueil)",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="services_page_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="section_images/",
                verbose_name="Image page liste Services",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="stack_section_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="section_images/",
                verbose_name="Image section Stack Technique",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="valeurs_section_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="section_images/",
                verbose_name="Image section Valeurs",
            ),
        ),
    ]
