# Generated by Django 5.1.6 on 2025-12-06 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_acceuil",
            "0023_section_title_image_siteprofile_bio_section_image_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section",
            name="title_image",
        ),
        migrations.RemoveField(
            model_name="siteprofile",
            name="bio_section_image",
        ),
        migrations.RemoveField(
            model_name="siteprofile",
            name="blog_home_image",
        ),
        migrations.RemoveField(
            model_name="siteprofile",
            name="blog_page_image",
        ),
        migrations.RemoveField(
            model_name="siteprofile",
            name="competences_section_image",
        ),
        migrations.RemoveField(
            model_name="siteprofile",
            name="experience_section_image",
        ),
        migrations.RemoveField(
            model_name="siteprofile",
            name="formation_section_image",
        ),
        migrations.RemoveField(
            model_name="siteprofile",
            name="interets_section_image",
        ),
        migrations.RemoveField(
            model_name="siteprofile",
            name="projects_home_image",
        ),
        migrations.RemoveField(
            model_name="siteprofile",
            name="projects_page_image",
        ),
        migrations.RemoveField(
            model_name="siteprofile",
            name="services_home_image",
        ),
        migrations.RemoveField(
            model_name="siteprofile",
            name="services_page_image",
        ),
        migrations.RemoveField(
            model_name="siteprofile",
            name="stack_section_image",
        ),
        migrations.RemoveField(
            model_name="siteprofile",
            name="valeurs_section_image",
        ),
    ]
