# Generated by Django 5.1.6 on 2025-12-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_acceuil", "0024_remove_section_title_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="title_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="section_images/",
                verbose_name="Image du titre",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="blog_home_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="section_images/",
                verbose_name="Image section Blog (Accueil)",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="blog_page_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="section_images/",
                verbose_name="Image page liste Blog",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="projects_home_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="section_images/",
                verbose_name="Image section Projets (Accueil)",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="projects_page_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="section_images/",
                verbose_name="Image page liste Projets",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="services_home_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="section_images/",
                verbose_name="Image section Services (Accueil)",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="services_page_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="section_images/",
                verbose_name="Image page liste Services",
            ),
        ),
    ]
