# Generated by Django 5.1.6 on 2025-12-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_acceuil",
            "0025_section_title_image_siteprofile_blog_home_image_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="siteprofile",
            name="bio_title_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="section_images/",
                verbose_name="Image du titre Bio",
            ),
        ),
    ]
