# Generated by Django 5.1.6 on 2025-12-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_acceuil", "0026_siteprofile_bio_title_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteprofile",
            name="blog_display_order",
            field=models.PositiveIntegerField(
                default=3, verbose_name="Ordre d'affichage Blog"
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="contact_display_order",
            field=models.PositiveIntegerField(
                default=5, verbose_name="Ordre d'affichage Contact"
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="projects_display_order",
            field=models.PositiveIntegerField(
                default=2, verbose_name="Ordre d'affichage Projets"
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="services_display_order",
            field=models.PositiveIntegerField(
                default=4, verbose_name="Ordre d'affichage Services"
            ),
        ),
    ]
