# Generated by Django 5.1.6 on 2025-12-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_acceuil", "0027_siteprofile_blog_display_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteprofile",
            name="contact_button_text",
            field=models.CharField(
                default="Envoyer le message",
                max_length=100,
                verbose_name="Texte du bouton",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="contact_company_label",
            field=models.CharField(
                default="Entreprise",
                max_length=100,
                verbose_name="Label champ Entreprise",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="contact_email_label",
            field=models.CharField(
                default="Adresse email",
                max_length=100,
                verbose_name="Label champ Email",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="contact_error_message",
            field=models.TextField(
                default="Une erreur s'est produite lors de l'envoi de votre message. Veuillez réessayer.",
                verbose_name="Message d'erreur",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="contact_intro_text",
            field=models.TextField(
                blank=True, verbose_name="Texte d'introduction Contact"
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="contact_message_label",
            field=models.CharField(
                default="Votre message",
                max_length=100,
                verbose_name="Label champ Message",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="contact_name_label",
            field=models.CharField(
                default="Nom complet", max_length=100, verbose_name="Label champ Nom"
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="contact_profession_label",
            field=models.CharField(
                default="Profession",
                max_length=100,
                verbose_name="Label champ Profession",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="contact_subject_label",
            field=models.CharField(
                default="Objet", max_length=100, verbose_name="Label champ Objet"
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="contact_success_message",
            field=models.TextField(
                default="Merci ! Votre message a été envoyé avec succès. Nous vous répondrons dans les plus brefs délais.",
                verbose_name="Message de succès",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="contact_title",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Titre de la section Contact"
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="contact_title_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="section_images/",
                verbose_name="Image du titre Contact",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="enable_confirmation_email",
            field=models.BooleanField(
                default=True,
                verbose_name="Envoyer un email de confirmation à l'expéditeur",
            ),
        ),
    ]
