# Generated by Django 5.1.6 on 2025-12-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_acceuil", "0028_contact_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteprofile",
            name="gmail_app_password",
            field=models.CharField(
                blank=True,
                help_text="Requis pour envoyer des emails. Créez-le sur https://myaccount.google.com/apppasswords",
                max_length=100,
                verbose_name="Mot de passe d'application Gmail",
            ),
        ),
    ]
