# Generated by Django 5.1.6 on 2025-12-09 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_acceuil",
            "0030_alter_education_details_alter_experience_details_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteprofile",
            name="bio",
        ),
    ]
