# Generated by Django 5.1.6 on 2025-12-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_acceuil", "0031_remove_siteprofile_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteprofile",
            name="bio_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="bio/", verbose_name="Image Bio"
            ),
        ),
    ]
