# Generated by Django 5.1.6 on 2025-12-09 03:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_acceuil", "0032_siteprofile_bio_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteprofile",
            name="bio_image",
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="bio",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, verbose_name="Bio"
            ),
        ),
    ]
