# Generated by Django 5.1.6 on 2025-12-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_acceuil", "0033_remove_siteprofile_bio_image_siteprofile_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteprofile",
            name="show_author",
            field=models.BooleanField(
                default=True, verbose_name="Afficher l'auteur sur les cartes"
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="show_profession",
            field=models.BooleanField(
                default=True, verbose_name="Afficher la profession sur les cartes"
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="show_publish_date",
            field=models.BooleanField(
                default=True,
                verbose_name="Afficher la date de publication sur les cartes",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="show_update_date",
            field=models.BooleanField(
                default=True,
                verbose_name="Afficher la date de mise à jour sur les cartes",
            ),
        ),
    ]
