# Generated by Django 5.1.6 on 2025-12-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_acceuil",
            "0034_siteprofile_show_author_siteprofile_show_profession_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteprofile",
            name="show_author",
        ),
        migrations.RemoveField(
            model_name="siteprofile",
            name="show_profession",
        ),
        migrations.RemoveField(
            model_name="siteprofile",
            name="show_publish_date",
        ),
        migrations.RemoveField(
            model_name="siteprofile",
            name="show_update_date",
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="show_author_detail",
            field=models.BooleanField(default=True, verbose_name="Auteur - Détails"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="show_author_home",
            field=models.BooleanField(default=True, verbose_name="Auteur - Accueil"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="show_author_list",
            field=models.BooleanField(default=True, verbose_name="Auteur - Liste"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="show_profession_detail",
            field=models.BooleanField(
                default=True, verbose_name="Profession - Détails"
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="show_profession_home",
            field=models.BooleanField(
                default=True, verbose_name="Profession - Accueil"
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="show_profession_list",
            field=models.BooleanField(default=True, verbose_name="Profession - Liste"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="show_publish_date_detail",
            field=models.BooleanField(default=True, verbose_name="Date pub - Détails"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="show_publish_date_home",
            field=models.BooleanField(default=True, verbose_name="Date pub - Accueil"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="show_publish_date_list",
            field=models.BooleanField(default=True, verbose_name="Date pub - Liste"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="show_update_date_detail",
            field=models.BooleanField(default=True, verbose_name="Date MAJ - Détails"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="show_update_date_home",
            field=models.BooleanField(default=True, verbose_name="Date MAJ - Accueil"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="show_update_date_list",
            field=models.BooleanField(default=True, verbose_name="Date MAJ - Liste"),
        ),
    ]
