# Generated by Django 5.1.6 on 2025-12-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_acceuil", "0035_remove_siteprofile_show_author_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteprofile",
            name="show_author_detail",
        ),
        migrations.RemoveField(
            model_name="siteprofile",
            name="show_author_home",
        ),
        migrations.RemoveField(
            model_name="siteprofile",
            name="show_author_list",
        ),
        migrations.RemoveField(
            model_name="siteprofile",
            name="show_profession_detail",
        ),
        migrations.RemoveField(
            model_name="siteprofile",
            name="show_profession_home",
        ),
        migrations.RemoveField(
            model_name="siteprofile",
            name="show_profession_list",
        ),
        migrations.RemoveField(
            model_name="siteprofile",
            name="show_publish_date_detail",
        ),
        migrations.RemoveField(
            model_name="siteprofile",
            name="show_publish_date_home",
        ),
        migrations.RemoveField(
            model_name="siteprofile",
            name="show_publish_date_list",
        ),
        migrations.RemoveField(
            model_name="siteprofile",
            name="show_update_date_detail",
        ),
        migrations.RemoveField(
            model_name="siteprofile",
            name="show_update_date_home",
        ),
        migrations.RemoveField(
            model_name="siteprofile",
            name="show_update_date_list",
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="blog_show_author_detail",
            field=models.BooleanField(default=True, verbose_name="Auteur"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="blog_show_author_home",
            field=models.BooleanField(default=True, verbose_name="Auteur"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="blog_show_author_list",
            field=models.BooleanField(default=True, verbose_name="Auteur"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="blog_show_profession_detail",
            field=models.BooleanField(default=True, verbose_name="Profession"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="blog_show_profession_home",
            field=models.BooleanField(default=True, verbose_name="Profession"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="blog_show_profession_list",
            field=models.BooleanField(default=True, verbose_name="Profession"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="blog_show_publish_date_detail",
            field=models.BooleanField(default=True, verbose_name="Date pub"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="blog_show_publish_date_home",
            field=models.BooleanField(default=True, verbose_name="Date pub"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="blog_show_publish_date_list",
            field=models.BooleanField(default=True, verbose_name="Date pub"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="blog_show_update_date_detail",
            field=models.BooleanField(default=True, verbose_name="Date MAJ"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="blog_show_update_date_home",
            field=models.BooleanField(default=True, verbose_name="Date MAJ"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="blog_show_update_date_list",
            field=models.BooleanField(default=True, verbose_name="Date MAJ"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="projects_show_author_detail",
            field=models.BooleanField(default=True, verbose_name="Auteur"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="projects_show_author_home",
            field=models.BooleanField(default=True, verbose_name="Auteur"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="projects_show_author_list",
            field=models.BooleanField(default=True, verbose_name="Auteur"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="projects_show_profession_detail",
            field=models.BooleanField(default=True, verbose_name="Profession"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="projects_show_profession_home",
            field=models.BooleanField(default=True, verbose_name="Profession"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="projects_show_profession_list",
            field=models.BooleanField(default=True, verbose_name="Profession"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="projects_show_publish_date_detail",
            field=models.BooleanField(default=True, verbose_name="Date pub"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="projects_show_publish_date_home",
            field=models.BooleanField(default=True, verbose_name="Date pub"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="projects_show_publish_date_list",
            field=models.BooleanField(default=True, verbose_name="Date pub"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="projects_show_update_date_detail",
            field=models.BooleanField(default=True, verbose_name="Date MAJ"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="projects_show_update_date_home",
            field=models.BooleanField(default=True, verbose_name="Date MAJ"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="projects_show_update_date_list",
            field=models.BooleanField(default=True, verbose_name="Date MAJ"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="services_show_author_detail",
            field=models.BooleanField(default=True, verbose_name="Auteur"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="services_show_author_home",
            field=models.BooleanField(default=True, verbose_name="Auteur"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="services_show_author_list",
            field=models.BooleanField(default=True, verbose_name="Auteur"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="services_show_profession_detail",
            field=models.BooleanField(default=True, verbose_name="Profession"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="services_show_profession_home",
            field=models.BooleanField(default=True, verbose_name="Profession"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="services_show_profession_list",
            field=models.BooleanField(default=True, verbose_name="Profession"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="services_show_publish_date_detail",
            field=models.BooleanField(default=True, verbose_name="Date pub"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="services_show_publish_date_home",
            field=models.BooleanField(default=True, verbose_name="Date pub"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="services_show_publish_date_list",
            field=models.BooleanField(default=True, verbose_name="Date pub"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="services_show_update_date_detail",
            field=models.BooleanField(default=True, verbose_name="Date MAJ"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="services_show_update_date_home",
            field=models.BooleanField(default=True, verbose_name="Date MAJ"),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="services_show_update_date_list",
            field=models.BooleanField(default=True, verbose_name="Date MAJ"),
        ),
    ]
