# Generated by Django 5.1.6 on 2025-12-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_acceuil", "0036_remove_siteprofile_show_author_detail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteprofile",
            name="navbar_position",
            field=models.CharField(
                choices=[("left", "Gauche"), ("right", "Droite")],
                default="left",
                help_text="Choisir si la barre de navigation doit être à gauche ou à droite",
                max_length=10,
                verbose_name="Position de la barre de navigation",
            ),
        ),
    ]
