# Generated by Django 5.1.6 on 2025-12-09 07:41

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="Slug"),
                ),
                (
                    "resume",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        verbose_name="Résumé"
                    ),
                ),
                (
                    "author_name",
                    models.CharField(
                        default="Youssoupha Marega",
                        max_length=100,
                        verbose_name="Nom de l'auteur",
                    ),
                ),
                (
                    "author_email",
                    models.EmailField(
                        default="contact@youssouphamarega.com",
                        max_length=254,
                        verbose_name="Email de l'auteur",
                    ),
                ),
                (
                    "author_profession",
                    models.CharField(
                        default="Data Scientist",
                        max_length=100,
                        verbose_name="Profession de l'auteur",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de publication"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("project", "Projet"),
                            ("blog", "Article de Blog"),
                            ("service", "Service"),
                        ],
                        default="project",
                        help_text="Sélectionnez le type : Projet, Article ou Service",
                        max_length=20,
                        verbose_name="Type de contenu",
                    ),
                ),
                (
                    "content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        help_text="Description complète avec images, mise en forme, etc.",
                        verbose_name="Contenu détaillé",
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="content/%Y/%m/",
                        verbose_name="Image principale",
                    ),
                ),
                (
                    "github_url",
                    models.URLField(
                        blank=True,
                        help_text="URL du dépôt GitHub du projet",
                        verbose_name="Lien GitHub (projets)",
                    ),
                ),
                (
                    "demo_url",
                    models.URLField(
                        blank=True,
                        help_text="URL de la démo ou du site en ligne",
                        verbose_name="Lien démo (projets)",
                    ),
                ),
                (
                    "calendly_url",
                    models.URLField(
                        blank=True,
                        help_text="URL pour réserver une consultation",
                        verbose_name="Lien Calendly (services)",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Prix du service (format: 99.99)",
                        max_digits=10,
                        null=True,
                        verbose_name="Prix (services)",
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        help_text="Exemple: '1 heure', '2 jours', 'Sur devis'",
                        max_length=100,
                        verbose_name="Durée (services)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contenu",
                "verbose_name_plural": "Contenu",
                "ordering": ["-created_at"],
            },
        ),
    ]
